version: '3'

services:
  web:
    build: ./web
    ports:
      - "5173:5173"
    depends_on:
      - server-go

  server-go:
    build: ./server-go
    ports:
      - "8080:8080"
    volumes:
      - ./server-go:/app